import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'

type StatusPageProps = { name: string }



const StatusPage: NextPage<StatusPageProps> = (props) => {



  const router = useRouter();

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-2xl lg:text-5xl font-black pb-6'>DESIGNER</h1>
            <Image src={`/AnyConv.com__ai.webp`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>戸澤愛梨</h1>
              <h2 className='font-light text-xl'>Airi Tozawa</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>取締役/デザイナー</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>2000年生まれ。株式会社TRYBE取締役。 彼女はデザイナーとVtuberという二つの顔を持つ異色のクリエイター。デザイン業務は『クライアントに寄り添う』をモットーに取り組んでおり、ロゴデザイン、YouTube のサムネイル制作、資料作成を行っている。Vtuberとしての活動も、独自のデザイン性を売りにして、毎日配信を続けることで根強いファンを作っている。</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>V liveアプリ「IRIAM」にて、月間ランキング1位を受賞。「関西大学フェスティバルin関西」のロゴコンペにて、ロゴデザインを担当し、優勝。 </p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>Email：a_tozawa@trybe.co.jp</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>Email：a_tozawa@trybe.co.jp</p>
              <div className='flex '>

                <Link href={`https://twitter.com/jr_tozawa`}>
                  <a >
                    <p className='text-md '>
                      <FontAwesomeIcon icon={faTwitter} width={20} />
                    </p>
                  </a>
                </Link>

                <Link href={`https://www.instagram.com/jr_tozawa/`}>
                  <a>
                    <p className='text-md pl-3 '>
                      <FontAwesomeIcon icon={faInstagram} width={20} />
                    </p>


                  </a>
                </Link>


              </div>
            </div>

          </div>
          <div className='text-center pb-20 text-sm lg:text-xl font-bold'>
            <Link href={"/members/sota"} ><a >＜ BACK</a></Link>　|　<Link href={"/members"}><a>BACK TO LIST</a></Link>　|　<Link href={"/members/shunsuke"}><a>NEXT ＞</a></Link>
          </div>

        </div>
      </main>


    </div>
  )
}

export default StatusPage
