import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='w-9/12 m-auto'>
        <ul className="border border-black  
 lg:grid lg:grid-cols-3 lg:flex-wrap">
            <li className="border border-black  mb-5">
              <Image src="/hinata.gif" width={500} height={300} alt=""  />
              <p>山口陽</p>
              <p>代表/企画屋</p>
            </li>
            <li className="border border-black mb-5">2</li>
            <li className="border border-black mb-5">3</li>

            <li className="border border-black mb-5">1</li>
            <li className="border border-black mb-5">2</li>
            <li className="border border-black mb-5">3</li>
          </ul>
        </div>
      </main>


    </div>
  )
}

export default Home
