import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'

type StatusPageProps = { name: string }



const StatusPage: NextPage<StatusPageProps> = (props) => {



  const router = useRouter();

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-3xl lg:text-5xl font-black pb-6'>Planner</h1>
            <Image src={`/taiki.gif`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>今泉大輝</h1>
              <h2 className='font-light text-xl'>Taiki Imaizumi</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>プランナー</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>2000年生まれ。SNSマーケティングを中心にマーケターとして成長を続ける一面もあれば、大学と連携したイベントの企画や絵本制作、ポスター制作の企画なども行う。自身の原体験から、心身に特性をもつ人にサービスを届けるという目標を持ち、その目標を目指し日々成長を続ける。</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>Instagramを利用した小説制作のプランニング。関西大学とkokoima主催のファッションショーの運営や服の作成やポスター制作。</p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>Email：t_imaizumi@trybe.co.jp</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>Email：t_imaizumi@trybe.co.jp</p>
              <div className='flex '>

               

                <Link href={`https://www.instagram.com/_izuminn_1230/`}>
                  <a>
                    <p className='text-md  '>
                      <FontAwesomeIcon icon={faInstagram} width={20} />
                    </p>


                  </a>
                </Link>


              </div>
            </div>

          </div>
          <div className='text-center pb-20 text-sm lg:text-xl font-bold'>
            <Link href={"/members/issei"} ><a >＜ BACK</a></Link>　|　<Link href={"/members"}><a>BACK TO LIST</a></Link><Link href={""}><a className='hidden'>NEXT ＞</a></Link>
          </div>
        </div>
      </main>


    </div>
  )
}

export default StatusPage
