import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'

type StatusPageProps = { name: string }



const StatusPage: NextPage<StatusPageProps> = (props) => {



  const router = useRouter();

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-3xl lg:text-5xl font-black pb-6'>INFLUENCER</h1>
            <Image src={`/AnyConv.com__taro.webp`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>辻本太郎</h1>
              <h2 className='font-light text-xl'>Taro Tsujimoto</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>インフルエンサー</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>1999年生まれ。TNK BASE シェアハウスの代表。 元バイク屋の空き地をリノベーションし、「TNK BASE」を立ち上げた発起人。視覚芸術を得意とし、文章や写真やアートを通して、多くの若者に影響を与えられる「発信力」と「人望」を持つ。また、旅人という側面もあり、TNK  BASEには日々新しい旅人が集まってくる。自身も全国各地を旅して回りながらイベントを開催している。</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>世界一周の夢を叶えるコンテスト 「DREAM」のファイナリスト。「海辺の映画祭」を主催。「日本一周×野外シネマ」の企画運営。 </p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>Email：crossbook0504@icloud.com</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>Email：crossbook0504@icloud.com</p>
              <div className='flex '>



                <Link href={`https://www.instagram.com/taroveller/`}>
                  <a>
                    <p className='text-md '>
                      <FontAwesomeIcon icon={faInstagram} width={20} />
                    </p>


                  </a>
                </Link>


              </div>
            </div>

          </div>
          <div className='text-center pb-20 text-xl font-bold'>
            <Link href={"/members/yuta"} ><a >＜ BACK</a></Link>　|　<Link href={"/members"}><a>BACK TO LIST</a></Link>　|　<Link href={"/members/jurin"}><a>NEXT ＞</a></Link>
          </div>

        </div>
      </main>


    </div>
  )
}

export default StatusPage
