import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'

type StatusPageProps = { name: string }



const StatusPage: NextPage<StatusPageProps> = (props) => {



  const router = useRouter();

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-3xl lg:text-5xl font-black pb-6'>PLANNER</h1>
            <Image src={`/AnyConv.com__yu.webp`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>井上友聖</h1>
              <h2 className='font-light text-xl'>Yusei Inoue</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>プランナー</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>2001年生まれ。株式会社TRYBEメンバー。 「変化や速さを求められる世の中で、自分の世界を大切に生きれる人を教育する」をモットーに、学生のメンターや起業家育成、企業のコンサルタントや、タレントのプロデュースなどの教育事業を中心に多岐にわたる役割を担っている。自身で企画立案も行っており、山を買うことを最終目標に「林間学校」という学生向けのキャリアイベントを運営している。</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>中学2年生時、仮想通貨に手をつけ101万円の利益を出す。当時のUSJの部長と「学生団体ZONE」を共同代表。企業コンサル2社、タレントやプロスポーツ選手の人生設計、セカンドキャリア支援、事業設計を請け負う。ディズニーライブにてキッズダンサーの経験あり。「林間学校」企画運営。</p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>TEL：080-3863-6557 / Email：y_inoue@trybe.co.jp</p>
              <p className='lg:hidden text-xs  leading-relaxed  font-bold'>TEL：080-3863-6557</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>Email：y_inoue@trybe.co.jp</p>
              <div className='flex '>

                <Link href={`https://twitter.com/yuseinemui`}>
                  <a >
                    <p className='text-md '>
                      <FontAwesomeIcon icon={faTwitter} width={20} />
                    </p>
                  </a>
                </Link>

                <Link href={`https://www.instagram.com/yusei.0401/`}>
                  <a>
                    <p className='text-md pl-3 '>
                      <FontAwesomeIcon icon={faInstagram} width={20} />
                    </p>


                  </a>
                </Link>


              </div>
            </div>

          </div>

        </div>
      </main>


    </div>
  )
}

export default StatusPage
