import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'

type StatusPageProps = { name: string }



const StatusPage: NextPage<StatusPageProps> = (props) => {



  const router = useRouter();

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-2xl lg:text-5xl font-black pb-6'>System Engineer</h1>
            <Image src={`/AnyConv.com__waki.webp`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>森脇弓貴</h1>
              <h2 className='font-light text-xl'>Yutaka Moriwaki</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>エンジニア</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>2001年生まれ。エンジニア団体si-cleのエンジニア担当。 主に企業のWebサイトやECサイトのコーディングを行っている。ただ単にコードを書いて終わりではなく、常日頃からユーザー目線に立つことにこだわっている。どんなに複雑なプログラムでも、機能するまでやりきる根性を持ち合わせている。また、エンジニアの枠組みに収まらず、経営の学習に取り組むなど、とても好奇心旺盛である。</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>Webサービス「口コミ複業パラキャリ」の制作。アパレルECサイト「Maison a la mode」の制作。株式会社TRYBEのWebサイト制作。</p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>Email：ytk0202@outlook.jp</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>Email：ytk0202@outlook.jp</p>
              <div className='flex '>



                <Link href={`https://www.instagram.com/0202waki/`}>
                  <a>
                    <p className='text-md '>
                      <FontAwesomeIcon icon={faInstagram} width={20} />
                    </p>


                  </a>
                </Link>


              </div>
            </div>

          </div>
          <div className='text-center pb-20 text-sm lg:text-xl font-bold'>
            <Link href={"/members/jurin"} ><a >＜ BACK</a></Link>　|　<Link href={"/members"}><a>BACK TO LIST</a></Link>　|　<Link href={"/members/issei"}><a>NEXT ＞</a></Link>
          </div>

        </div>
      </main>


    </div>
  )
}

export default StatusPage
