import type { NextPage } from 'next'
import Head from 'next/head'
import Img from 'next/image'
import Link from 'next/link'
import { type } from 'os'
import Jinro from '../../components/Project-jinro'
import Seishun from '../../components/Project-seisyun'
import Yatai from '../../components/Project-yatai'
import Santa from '../../components/Project-santa'
import Works from '../../components/Works'
const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='font-body mt-24 mb-20 w-9/12 m-auto'>
        <section id="projects">
          <h1 className='text-center mb-12 text-4xl font-bold'>Projects</h1>


          <div>
            
            <div className='grid lg:grid-cols-2 gap-2'>
              <Jinro />
              <Seishun />
              <Yatai />
              <Santa />
            </div>
          </div>
        </section>
        <section id="works">
        <Works />
        </section>
      </main>
    </div>
  )
}
export default Home