import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import "remixicon/fonts/remixicon.css";
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body bg-gray-100'>
        <div className='w-10/12 lg:w-8/12 m-auto'>
          <div className='text-center pt-20 w-full'>
            <h1 className='text-3xl lg:text-5xl font-black pb-6'>PLANNER</h1>
            <Image src={`/${router.query.image}`} width={1300} height={750} alt="" className='' />

          </div>
          <div className='lg:flex pb-20 pt-3'>
            <div className='lg:w-4/12'>
              <h1 className='font-extrabold text-2xl'>{router.query.name}</h1>
              <h2 className='font-light text-xl'>{ router.query.nameRoma }</h2>
              <p className='pt-4 pb-8 lg:pb-0 lg:pt-8 text-sm font-bold'>{router.query.position}</p>
            </div>
            <div className='lg:w-8/12'>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>{router.query.introduction}</p>
              <p className='text-xs lg:text-sm  leading-relaxed font-bold pb-6'>{router.query.achievement}</p>
              <p className='hidden lg:block text-xs  leading-relaxed pb-6 font-bold'>{router.query.tel} / {router.query.email}</p>
              <p className='lg:hidden text-xs  leading-relaxed  font-bold'>{router.query.tel}</p>
              <p className='lg:hidden text-xs  leading-relaxed pb-6 font-bold'>{router.query.email}</p>
            </div>
          </div>
          <p></p>
        </div>
      </main>


    </div>
  )
}

export default Home
