import Head from 'next/head'

const Headtag = () => {
 return( <div>
    <Head>
      <title>TRYBE.inc</title>
      <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
     <link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet"></link>
    </Head>
  </div>
 )
}

export default Headtag;