import Head from 'next/head'

const Headtag = () => {
 return( <div>
    <Head>
      <title>TRYBE.inc</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </div>
 )
}

export default Headtag;