import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About';
import Img from 'next/image'
import Pertoner from '../components/Pertoner.js';
import Contactbtn from '../components/Contactbtn.js';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
        <div className='w-10/12 lg:w-9/12 m-auto font-body'>
          <About />
            <div className='mt-20'>
              <h1 className='text-center text-3xl '>Profile</h1>
            <table className='text-sm w-full lg:w-10/12 m-auto mt-10 '>
                <tr className='py-5 '>
                <th className='border-b-2 border-black py-4'>会社名</th>
                <td className='text-center border-b border-red'>TRYBE Inc.（株式会社トライブ）</td>
              </tr>
              
              <tr className=''>
                <th className='border-b-2 border-black py-4'>設立</th>
                <td className='text-center border-b border-red'>2020/12/01</td>
              </tr>
              
              <tr className=''>
                <th className='border-b-2 border-black py-4'>役員</th>
                <td className='text-center border-b border-red'>山口陽,山本健太,稲田創太,戸澤愛梨</td>
              </tr>
              
              <tr className=''>
                <th className='border-b-2 border-black py-4'>資本金</th>
                <td className='text-center border-b border-red'>50万円</td>
              </tr>
              
              <tr className=''>
                <th className='border-b-2 border-black py-4'>Mail</th>
                <td className='text-center border-b border-red'>info@trybe.co.jp</td>
              </tr>

              <tr className='py-4'>
                <th className='border-b-2 border-black'>TEL</th>
                <td className='text-center border-b border-red  py-4'>08061039185</td>
              </tr>

              <tr className=''>
                <th className='border-b-2 border-black py-4'>住所</th>
                <td className='text-center border-b border-red'> 〒577-0027 大阪府東大阪市新家中町5-29 TNK base </td>
              </tr>
              
              </table>
          </div>
          <div className='mt-20'>
            <h1 className='text-center text-3xl mb-5'>Partoners</h1>
            <Pertoner />
          </div>
          <div className='mt-20 mb-10 text-center'>
            <h1 className='text-center text-3xl mb-5'>Contact</h1>
            <Contactbtn />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
