import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-body'>
          <div className='w-10/12 m-auto'>
            <h1 className=' text-3xl lg:text-4xl mt-20 font-bold'>Contact.</h1>
            <span className='text-1xl'>お問い合わせ</span>
            <p className='text-center mt-8 mb-8 text-xs lg:text-lg'>下記のフォームをご記入の上、 お問い合わせください。</p>
          </div>


          <div className='w-9/12 m-auto lg:w-7/12'>
            <label className='block font-bold pb-3 ' htmlFor="">お問い合わせの種類*</label>
            <select className='w-full bg-gray-100 p-1 h-14 lg:h-16' name="" id="">
              <option disabled>選択してください</option>
              <option value="">新規お取引に関して</option>
              <option value="">採用に関して</option>
            </select>
          </div>
          <div className='w-9/12 m-auto pt-8 lg:w-7/12'>
            <label className='block font-bold pb-3' htmlFor="">お名前*</label>
            <input className='w-full bg-gray-100 p-2 h-14 lg:h-16' name="" id="" placeholder='サイクル太郎'>
            </input>
          </div>
          <div className='w-9/12 m-auto pt-8 lg:w-7/12'>
            <label className='block font-bold pb-3' htmlFor="">メールアドレス*</label>
            <input className='w-full bg-gray-100 p-2 h-14 lg:h-16' name="" id="" placeholder='xxx@example.com'>
            </input>
          </div>
          <div className='w-9/12 m-auto pt-8 lg:w-7/12'>
            <label className='block font-bold pb-3' htmlFor="">お問い合わせ内容*</label>
            <textarea className='w-full bg-gray-100 h-40 p-2' name="" id="" placeholder='お問い合わせ内容を入力してください'>
            </textarea>
          </div>

        <div className='text-center mt-10 mb-20 border border-gray-300  w-9/12 m-auto py-5 lg:w-7/12 hover:bg-gray-800 hover:text-white duration-200'>
            <Link href='/contact'><a className='font-bold'>確認画面へ</a></Link>
          </div>
        </main>
      

    </div>
  )
}

export default Home
